#ifndef VGA_H
#define VGA_H

// default size for VGA buffer
#define VGA_SIZE_WIDTH 80
#define VGA_SIZE_HEIGHT 25

// vga address/port
#define VGA_TEXT_MODE_VIDEO_MEMORY_BUFFER 0xB8000
#define VGA_CONTROLLER_PORT_LOW 0x3D4
#define VGA_CONTROLLER_PORT_HIGH 0x3D5

// color mode constant
enum VGA_COLOR
{
    VGA_COLOR_BLACK = 0,
    VGA_COLOR_BLUE = 1,
    VGA_COLOR_GREEN = 2,
    VGA_COLOR_CYAN = 3,
    VGA_COLOR_RED = 4,
    VGA_COLOR_MAGENTA = 5,
    VGA_COLOR_BROWN = 6,
    VGA_COLOR_LIGHT_GREY = 7,
    VGA_COLOR_DARK_GREY = 8,
    VGA_COLOR_LIGHT_BLUE = 9,
    VGA_COLOR_LIGHT_GREEN = 10,
    VGA_COLOR_LIGHT_CYAN = 11,
    VGA_COLOR_LIGHT_RED = 12,
    VGA_COLOR_LIGHT_MAGENTA = 13,
    VGA_COLOR_LIGHT_BROWN = 14,
    VGA_COLOR_WHITE = 15,
};

#endif
